/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BlockChain;

import static BlockChain.Block.lastBlock;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ZohaibAbbasZA
 */
public class Transaction extends javax.swing.JFrame {
    private String inEmail;
    public String prevHasher;
    private final Users sender = new Users();
    private final Users taker = new Users(); 
    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
        moneyL.setVisible(false);
        moneyF.setVisible(false);
        send.setVisible(false);
        
    }
    public Transaction(String a,String b)
    {
        
        initComponents();
        inEmail=a;
        prevHasher=b;
        moneyL.setVisible(false);
        moneyF.setVisible(false);
        send.setVisible(false);
    }
       public void close(){
	WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
	Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        uName = new javax.swing.JLabel();
        searchF = new javax.swing.JTextField();
        searchB = new javax.swing.JButton();
        searchL = new javax.swing.JLabel();
        moneyF = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        moneyL = new javax.swing.JLabel();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        uName.setBackground(new java.awt.Color(255, 255, 255));
        uName.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        uName.setForeground(new java.awt.Color(255, 255, 255));
        uName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uName.setText("Transaction Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        searchF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFActionPerformed(evt);
            }
        });

        searchB.setBackground(new java.awt.Color(255, 255, 255));
        searchB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BlockChain/Capture3.JPG"))); // NOI18N
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });

        searchL.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        searchL.setText("Search People by Email");

        moneyF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyFActionPerformed(evt);
            }
        });

        send.setBackground(new java.awt.Color(153, 0, 153));
        send.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        send.setForeground(new java.awt.Color(255, 255, 255));
        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        moneyL.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        moneyL.setText("Enter Money");

        close.setBackground(new java.awt.Color(153, 0, 153));
        close.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("Exit");
        close.setBorder(null);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneyL, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchL)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(moneyF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(searchB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(moneyL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moneyF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFActionPerformed

    private void moneyFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyFActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        String sendAmount="";
        long amount=0;
        try{
        sendAmount = moneyF.getText();
        amount= Long.parseLong(sendAmount);
        }
          catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane,"Invalid Input");
        }
        sender.setEmail(inEmail);
        int i = 0;
        try {
           FileReader file = new FileReader(inEmail);
           BufferedReader reader = new BufferedReader(file);
           String line;
           while((line=reader.readLine())!= null)
           {
               i++;
               if(i == 1)
               {
                   
               }
               if(i == 2)
               {
               sender.setPassword(line);
               }
               if(i == 3)
               {
                   sender.setUserName(line);
               }
               if(i == 4)
               {
                   sender.setMoney(line);
               }
           }
           
       } catch (FileNotFoundException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        long smoney = Long.parseLong(sender.getMoney());
           
           long rmoney = Long.parseLong(taker.getMoney());
           String ems = sender.getEmail();
           String emt = taker.getEmail();
           if(amount <=0)
           {
               JOptionPane.showMessageDialog(rootPane,"Invalid Input");
           }
           else{
            if(ems.equals(emt))
           {
               JOptionPane.showMessageDialog(rootPane,"Can't Create a Transaction with yourself.");
           }
           else if(!ems.equals(emt))
           {
           if(amount <= smoney)
           {
               smoney=smoney-amount;
               rmoney=rmoney+amount;
               String a = Long.toString(rmoney);
               String c = Long.toString(smoney);
               taker.setMoney(a);
               sender.setMoney(c);
               JOptionPane.showMessageDialog(rootPane,"Transaction Successful");
           

        try{
            PrintWriter writer = new PrintWriter(inEmail);
            writer.print("");
            writer.close();
            FileWriter writern = new FileWriter(inEmail,true);
            writern.write(sender.getEmail());
            writern.write("\n");
            writern.write(sender.getPassword());
            writern.write("\n");
            writern.write(sender.getUserName());
            writern.write("\n");
            writern.write(sender.getMoney());
            writern.close();
           
          }
        catch(Exception e)
        {
           
        }
        try{
            PrintWriter writer = new PrintWriter(taker.getEmail());
            writer.print("");
            writer.close();
            FileWriter writern = new FileWriter(taker.getEmail(),true);
            writern.write(taker.getEmail());
            writern.write("\n");
            writern.write(taker.getPassword());
            writern.write("\n");
            writern.write(taker.getUserName());
            writern.write("\n");
            writern.write(taker.getMoney());
            writern.close();
           
          }
        catch(Exception e)
        {
           
        }
           
        Block b = new Block();
         b.createBlock(sender.getEmail(), taker.getEmail(), sendAmount);
         
         String time=Long.toString(lastBlock.time);
         System.out.println(time);
         if(prevHasher == "null" )
         {
            prevHasher="null";
         }
         try{
            FileWriter writern = new FileWriter("blockchain",true);
            if(prevHasher != "null" )
            {
                writern.write("\n");
            }
            writern.write(sender.getEmail());
            writern.write("\n");
            writern.write(taker.getEmail());
            writern.write("\n");
            writern.write(sendAmount);
            writern.write("\n");
            writern.write(time);
            writern.write("\n");
            writern.write(lastBlock.hash);
            writern.write("\n");
            writern.write(prevHasher);
            writern.close();
          }
        catch(Exception e)
        {
           
        }
         File file = new File("community\\blockchain");
         file.getParentFile().mkdirs();
         try{
            FileWriter writern = new FileWriter(file,true);
            if(prevHasher != "null" )
            {
                writern.write("\n");
            }
            writern.write(sender.getEmail());
            writern.write("\n");
            writern.write(taker.getEmail());
            writern.write("\n");
            writern.write(sendAmount);
            writern.write("\n");
            writern.write(time);
            writern.write("\n");
            writern.write(lastBlock.hash);
            writern.write("\n");
            writern.write(prevHasher);
            writern.close();
          }
        catch(Exception e)
        {
           
        }
        
           }
        else
           {
               JOptionPane.showMessageDialog(rootPane,"Sorry Not Enough Coins");
            
               
           }
                    }
           }
            
         close();
         
    }//GEN-LAST:event_sendActionPerformed

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        //setUndecorated(true);
        String fileU= searchF.getText();
        taker.setEmail(fileU);
        int i = 0;
       try {
           FileReader file = new FileReader(fileU);
           BufferedReader reader = new BufferedReader(file);
           String line;
           while((line=reader.readLine())!= null)
           {
               i++;
               if(i == 1)
               {
                   
               }
               if(i == 2)
               {
               taker.setPassword(line);
               }
               if(i == 3)
               {
                   taker.setUserName(line);
               }
               if(i == 4)
               {
                   taker.setMoney(line);
               }
           }
           JOptionPane.showMessageDialog(rootPane,"User Found");
        moneyL.setVisible(true);
        moneyF.setVisible(true);
        send.setVisible(true);
       } catch (FileNotFoundException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(rootPane,"No such User Found");
       } catch (IOException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_searchBActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        close();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Transaction t = new Transaction();
                t.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField moneyF;
    private javax.swing.JLabel moneyL;
    private javax.swing.JButton searchB;
    private javax.swing.JTextField searchF;
    private javax.swing.JLabel searchL;
    private javax.swing.JButton send;
    private javax.swing.JLabel uName;
    // End of variables declaration//GEN-END:variables
}
